### ISSUE TITLE
Add version number to footer

### ISSUE THREAD

**Issue by bahadasx** [bbengfort/baleen#45]
The version number was removed from the header of the status page to make the format consistent with the rest of the site.  The footer seems like the best place to add it back in unless we add an "About" page at some point.

**Comment by bbengfort** [comment]
Yes - a clear display of the version number would be great, and the footer
seems like a good idea. I typically will make a tiny RESTful endpoint that
contains the status of the app, the current date time, and the current
version. I then add some jQuery/Javascript to the footer to use that
endpoint to poll for the app's status. I can show you more if you'd like.

Otherwise, we'll just have to embed the version as a context variable in
every single view we've created and render it in the template.

**Comment by janetriley** [comment]
There's a pull request in my fork.
